name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - name: Build
    #   run: cargo build --verbose

    # - name: Run tests
    #   run: cargo test --verbose

    # - name: Print PWD
    #   run: echo "pwd=$(pwd)"

    # - name: Change PWD
    #   run: echo "cd .."

    # - name: Print PWD
    #   run: echo "pwd=$(pwd)"


    - name: Build deltoid
      run: cargo build --manifest-path /home/runner/work/deltoid//deltoid/Cargo.toml --verbose

    - name: Run tests for deltoid
      run: cargo test --manifest-path /home/runner/work/deltoid//deltoid/Cargo.toml --verbose

    - name: Build deltoid (--features="snapshot")
      run: cargo build --manifest-path /home/runner/work/deltoid//deltoid/Cargo.toml --verbose --features="snapshot"

    - name: Run tests for deltoid (--features="snapshot")
      run: cargo test --manifest-path /home/runner/work/deltoid//deltoid/Cargo.toml --verbose --features="snapshot"


    - name: Build deltoid-derive
      run: cargo build --manifest-path /home/runner/work/deltoid//deltoid-derive/Cargo.toml --verbose

    - name: Run tests for deltoid-derive
      run: cargo test --manifest-path /home/runner/work/deltoid//deltoid-derive/Cargo.toml --verbose

    - name: Build deltoid-derive (--features="snapshot")
      run: cargo build --manifest-path /home/runner/work/deltoid//deltoid-derive/Cargo.toml --verbose --features="snapshot"

    - name: Run tests for deltoid-derive (--features="snapshot")
      run: cargo test --manifest-path /home/runner/work/deltoid//deltoid-derive/Cargo.toml --verbose --features="snapshot"
