name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - name: Build
    #   run: cargo build --verbose

    # - name: Run tests
    #   run: cargo test --verbose

    # - name: Print PWD
    #   run: echo "pwd=$(pwd)"

    # - name: Change PWD
    #   run: echo "cd .."

    # - name: Print PWD
    #   run: echo "pwd=$(pwd)"


    - name: Build deltoid
      working-directory: deltoid
      run: cargo build --verbose

    - name: Run tests for deltoid
      working-directory: deltoid
      run: cargo test  --verbose

    - name: Build deltoid (--features="snapshot")
      working-directory: deltoid
      run: cargo build --verbose --features="snapshot"

    - name: Run tests for deltoid (--features="snapshot")
      working-directory: deltoid
      run: cargo test --verbose --features="snapshot"


    - name: Build deltoid-derive
      working-directory: deltoid-derive
      run: cargo build --verbose

    - name: Run tests for deltoid-derive
      working-directory: deltoid-derive
      run: cargo test --verbose

    - name: Build deltoid-derive (--features="snapshot")
      working-directory: deltoid-derive
      run: cargo build --verbose --features="snapshot"

    - name: Run tests for deltoid-derive (--features="snapshot")
      working-directory: deltoid-derive
      run: cargo test --verbose --features="snapshot"
