name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: icepuma/rust-action@master

    - name: Build deltoid
      working-directory: deltoid
      run: cargo build --verbose

    - name: Run tests for deltoid
      working-directory: deltoid
      run: cargo test  --verbose

    - name: Build deltoid (--features="snapshot")
      working-directory: deltoid
      run: cargo build --verbose --features="snapshot"

    - name: Run tests for deltoid (--features="snapshot")
      working-directory: deltoid
      run: cargo test --verbose --features="snapshot"

    - name: Build deltoid-derive
      working-directory: deltoid-derive
      run: cargo build --verbose

    - name: Run tests for deltoid-derive
      working-directory: deltoid-derive
      run: cargo test --verbose

      # NOTE: Don't perform "snapshot" builds for the `deltoid-derive` crate,
      #       as that feature is only available for the `deltoid` crate.
